# Generated by Django 2.2.4 on 2019-09-07 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import entity.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=entity.models.Entity.reference, max_length=255, unique=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_phone_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="Entity's status in the system", verbose_name='Status')),
                ('is_provider', models.BooleanField(default=False, help_text='Check if this entity is the provider of this plateform', verbose_name='Provider')),
                ('country', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Country')),
                ('currency', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.CurrencyArea')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=entity.models.Pos.reference, max_length=255, unique=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('contact_phone_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="POS's status in the system", verbose_name='Status')),
                ('country', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Country')),
                ('entity', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Entity')),
                ('user', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pos',
                'verbose_name_plural': 'Pos',
            },
        ),
        migrations.CreateModel(
            name='EntityBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=entity.models.EntityBalance.reference, max_length=255, unique=True)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="POS's status in the system", verbose_name='Status')),
                ('entity', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Entity')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='entity.EntityBalance')),
            ],
            options={
                'verbose_name': 'Pos',
                'verbose_name_plural': 'Pos',
            },
        ),
    ]
