# Generated by Django 2.2.4 on 2019-09-07 16:58

from django.db import migrations, models
import entity.models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitybalance',
            options={'verbose_name': 'Entity balance', 'verbose_name_plural': "Entities' balance"},
        ),
        migrations.AlterField(
            model_name='entity',
            name='reference',
            field=models.CharField(default=entity.models.Entity.reference, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='entitybalance',
            name='reference',
            field=models.CharField(default=entity.models.EntityBalance.reference, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='reference',
            field=models.CharField(default=entity.models.Pos.reference, max_length=255, unique=True),
        ),
    ]
