# Generated by Django 2.2.4 on 2019-09-11 12:13

from django.db import migrations, models
import entity.models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_auto_20190911_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitybalance',
            name='comments',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='reference',
            field=models.CharField(default=entity.models.Entity.reference, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='entitybalance',
            name='reference',
            field=models.CharField(default=entity.models.EntityBalance.reference, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='reference',
            field=models.CharField(default=entity.models.Pos.reference, max_length=255, unique=True),
        ),
    ]
