
API_ERRORS = {
"ENTITY_STATUS_ERROR" : -100,
"PARTNER_STATUS_ERROR" : -101,
"INSUFFICIENT_BALANCE_ERROR" : -102,
"REDIS_KEY_LOCK_ERROR" : -103,
"REDIS_WATCH_LOCK_ERROR" : -104,
"INCORRECT_ENTITY_OR_INCORRECT_ENTITY_STATUS" : -105,
"INCORRECT_SERVICE_OR_INCORRECT_SERVICE_STATUS" : -106,
"UNKNOWN_ERROR" : -107,
"REDIS_CONNECTION_ERROR" : -108,
"METHOD_NOT_YET_SUPPORTED_ERROR" : -109,
"CONNECTION_TO_PARTNER_ERROR" : -110,
}
