# Generated by Django 2.2.4 on 2019-09-07 16:58

from django.db import migrations, models
import django.db.models.deletion
import partner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=partner.models.Partner.reference, max_length=255, unique=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_phone_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="Partner's status in the system", verbose_name='Status')),
                ('currency', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.CurrencyArea')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=partner.models.Service.reference, max_length=255, unique=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('max_retries', models.PositiveIntegerField(default=True)),
                ('status', models.BooleanField(default=True, help_text="Service's status in the system", verbose_name='Status')),
                ('partner', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partner.Partner')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='PartnerBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=partner.models.PartnerBalance.reference, max_length=255, unique=True)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('status', models.BooleanField(default=True, help_text="POS's status in the system", verbose_name='Status')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='partner.PartnerBalance')),
                ('partner', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partner.Partner')),
            ],
            options={
                'verbose_name': 'Pos',
                'verbose_name_plural': 'Pos',
            },
        ),
    ]
