# Generated by Django 2.2.4 on 2019-09-07 17:39

from django.db import migrations, models
import partner.models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20190907_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerbalance',
            options={'verbose_name': 'Prtner Balance'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='reference',
            field=models.CharField(default=partner.models.Partner.reference, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='partnerbalance',
            name='reference',
            field=models.CharField(default=partner.models.PartnerBalance.reference, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='reference',
            field=models.CharField(default=partner.models.Service.reference, max_length=255, unique=True),
        ),
    ]
