# Generated by Django 2.2.4 on 2019-09-18 10:12

from django.db import migrations, models
import partner.models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20190909_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='demo_base_url',
            field=models.CharField(default='http://', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='prod_base_url',
            field=models.CharField(default='http://', max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='reference',
            field=models.CharField(default=partner.models.Partner.reference, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='partnerbalance',
            name='reference',
            field=models.CharField(default=partner.models.PartnerBalance.reference, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='ping_status',
            field=models.BooleanField(default=False, help_text="Service's activity status in the system", verbose_name='Service activity status'),
        ),
        migrations.AlterField(
            model_name='service',
            name='reference',
            field=models.CharField(default=partner.models.Service.reference, max_length=255, unique=True),
        ),
    ]
