# Generated by Django 2.2.4 on 2019-09-07 17:39

from django.db import migrations, models
import django.db.models.deletion
import transaction.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('entity', '0004_auto_20190907_1739'),
        ('partner', '0004_auto_20190907_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=transaction.models.Transaction.reference, max_length=255, unique=True)),
                ('input_data', models.TextField(max_length=1000)),
                ('output_data', models.TextField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('retries_count', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=False, help_text='Transaction transmission status', verbose_name='Status')),
                ('result', models.BooleanField(default=False, help_text='Partner result summary', verbose_name='Transaction result')),
                ('currency', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.CurrencyArea')),
                ('entity', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Entity')),
                ('partner', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partner.Partner')),
                ('pos', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entity.Pos')),
                ('service', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partner.Service')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionBalanceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=transaction.models.TransactionBalanceDetail.reference, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('entity_account', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entity.EntityBalance')),
                ('partner_account', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partner.PartnerBalance')),
                ('transaction', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.Transaction')),
            ],
            options={
                'verbose_name': 'Transaction balance detail',
            },
        ),
    ]
